site_name: 'Theta Wiki'
docs_dir: 'docs'

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    - admonition
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - abbr
    - pymdownx.snippets:
        auto_append:
            - abbreviations.md

plugins:
    - search
    - awesome-pages:
        collapse_single_pages: true

theme: 
    name: material
    logo: assets/icon.png

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
