name: test-xcfa-sv-benchmarks
'on':
  workflow_dispatch: null
jobs:
  build:
    name: Build theta-xcfa-cli
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup and execute Gradle 'build' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: theta-xcfa-cli:build
      - run: mv subprojects/xcfa/xcfa-cli/build/libs/theta-xcfa-cli-*-all.jar theta.jar
      - uses: actions/upload-artifact@v3
        with:
          name: theta.jar
          path: theta.jar

  assemble:
    name: Assemble theta.zip
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: theta.jar
      - run: cp scripts/theta-start.sh ./
      - run: mkdir solvers
      - run: zip theta.zip theta.jar theta-start.sh lib solvers -r
      - uses: actions/upload-artifact@v3
        with:
          name: theta.zip
          path: theta.zip

  benchmarkSuite:
    name: Create a fairly minimal benchmark suite from sv-benchmarks
    runs-on:
      - ubuntu-latest
    steps:
      - run: git clone --no-checkout https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/
      - run: |
          cd sv-benchmarks
          git sparse-checkout set --no-cone "c/ReachSafety*.set" "c/ConcurrencySafety-*.set" c/NoDataRace-Main.set "c/**/*.prp"
          cat c/*set | awk 'NF' | sed '/^#/d' | sed 's/^/c\//' >> .git/info/sparse-checkout 
          git sparse-checkout reapply
          for i in c/*.set; do for taskCollection in $(cat $i | awk 'NF' | sed '/^#/d' ); do for task in $(bash -c "echo c/$taskCollection"); do echo ${task#c/}; done | head -n5; done > ${i%.set}-smoketest.set; done
          echo "c/ReachSafety*.set" "c/ConcurrencySafety-*.set" c/NoDataRace-Main.set "c/**/*.prp" > .git/info/sparse-checkout
          for i in $(cat c/*-smoketest.set); do echo c/$i >> .git/info/sparse-checkout; done
          git sparse-checkout reapply
          for i in $(cat c/*-smoketest.set); do cat c/$i | grep input_files | awk ' { print $2 } ' | xargs printf "c/%s/%s\n" $(dirname $i) >> .git/info/sparse-checkout; done
          git sparse-checkout reapply
          for i in c/*-smoketest.set; do mv $i ${i%-smoketest.set}.set; done
      - run: zip sv-benchmarks.zip sv-benchmarks
      - uses: actions/upload-artifact@v3
        with:
          name: sv-benchmarks.zip
          path: sv-benchmarks.zip

  test:
    name: Test xcfa-cli with benchexec
    needs: 
      - assemble
      - benchmarkSuite
    runs-on: ubuntu-latest
    container:
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: theta.zip
      - uses: actions/download-artifact@v3
        with:
          name: sv-benchmarks.zip
      - run: |
          mkdir theta
          cd theta
          unzip ../theta.zip
      - run: unzip sv-benchmarks.zip
      - run: add-apt-repository ppa:sosy-lab/benchmarking && apt update && apt install benchexec -y
      - run: |
          cd theta 
          wget https://gitlab.com/sosy-lab/sv-comp/bench-defs/-/raw/main/benchmark-defs/theta.xml
          benchexec theta.xml --read-only-dir / --overlay-dir /home
